import ibm_db
hostname="ba99a9e6-d59e-4883-8fc0-d6a8c9f7a08f.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud"
uid="djy96762"
pwd="cNFJRrdL17ah7wbW"
driver="{IBM DB2 ODBC DRIVER}"
db="bludb"
port="31321"
protocol="TCPIP"
cert="Cert.crt"

dsn=(
    "DRIVER={0};"
    "DATABASE={0};"
    "HOSTNAME={1};"
    "PORT={2};"
    "UID={3};"
    "SECURITY=SSL;"
    "SSLServerCertificate={4};"
    "PWD={5};").format(db,hostname,port,uid,cert,pwd)

print(dsn)
try:
    db2=ibm_db.connect(dsn,"","")
    print("connected to database")
except:
    print("unable to connect",ibm_db.conn_errormsg())
